### ISSUE TITLE
hunger free OK data cleanup

### ISSUE THREAD

**Issue by chimchim237** [codefortulsa/summer-meals-sites#1]
CSV looks like it needs some work; names of sites are in all caps.  comma, tab delimiters seem to be missing.

**Comment by smilesbright** [comment]
I didn't see any delimiter issues with the current version in master. I think I will expand the abbreviations of elementary and high school in the names and try to capitalize correctly. Any idea what the codes in parentheses mean in the site names?

**Comment by chimchim237** [comment]
I've got some better files from Richard to upload; will do that here in a bit.
