### ISSUE TITLE
geotag summer meals locations

### ISSUE THREAD

**Issue by chimchim237** [codefortulsa/summer-meals-sites#2]
Hunger Free OK data need lat/long for all locations.

**Comment by jdungan** [comment]
This is a simple geocoder using the census service:
https://github.com/codefortulsa/landuse/blob/master/services/us-census-geocoder.js

**Comment by chimchim237** [comment]
THANKS!
Mapbox also lets you edit the geojson file directly, using their visual editor. You can search for an address, and then it gives you the lat/long that you add as a data point to the set of locations.  I've done 10 so far, just for testing purposes.

**Comment by smilesbright** [comment]
Nice that geocoder is way more accurate than Bing Maps. Can use that instead of Mapbox which seems to be paid.

**Comment by chimchim237** [comment]
mapbox is free to a certain point: https://www.mapbox.com/pricing/ 
and the usage will probably be low enough that we won't have to worry about cost a whole lot (...even if we do; hunger free will more than likely be happy to pay).  i have a free account just to go through their tutorials and such, and it's not cost me anything to use their service.  it's really nice.

**Comment by chimchim237** [comment]
I'm going to mark this as solved, as we've just gotten a new file with all the lat / long already in there. Might need a little cleanup, but most of the work is there.
