### ISSUE TITLE
CSV of locations to a geojson file

### ISSUE THREAD

**Issue by chimchim237** [codefortulsa/summer-meals-sites#3]
Turn the list of locations in to a nicely formatted geojson file.

**Comment by smilesbright** [comment]
Hi @chimchim237 I forked the project and wrote a manual script for this here: https://github.com/smilesbright/summer-meals-sites. I used the Bing API to get coordinates, which while free is much less accurate. So I plan to look more at that Mapbox API next. 

I tested it with all the sites in Tulsa which I outputted to output.geojson. I'm thinking we can use the geojson as a simple data storage file on the server. Right now I have all info columns in properties and so I will probably move them over to another field so they don't show up in the marker pop ups.
